// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type senderPacketTs struct {
	_   structs.HostLayout
	Seq uint32
	Ts  [4]uint64
}

// loadSender returns the embedded CollectionSpec for sender.
func loadSender() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SenderBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sender: %w", err)
	}

	return spec, err
}

// loadSenderObjects loads sender and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*senderObjects
//	*senderPrograms
//	*senderMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSenderObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSender()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// senderSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type senderSpecs struct {
	senderProgramSpecs
	senderMapSpecs
	senderVariableSpecs
}

// senderProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type senderProgramSpecs struct {
	SenderIn  *ebpf.ProgramSpec `ebpf:"sender_in"`
	SenderOut *ebpf.ProgramSpec `ebpf:"sender_out"`
}

// senderMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type senderMapSpecs struct {
	Hist   *ebpf.MapSpec `ebpf:"hist"`
	Output *ebpf.MapSpec `ebpf:"output"`
}

// senderVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type senderVariableSpecs struct {
}

// senderObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type senderObjects struct {
	senderPrograms
	senderMaps
	senderVariables
}

func (o *senderObjects) Close() error {
	return _SenderClose(
		&o.senderPrograms,
		&o.senderMaps,
	)
}

// senderMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type senderMaps struct {
	Hist   *ebpf.Map `ebpf:"hist"`
	Output *ebpf.Map `ebpf:"output"`
}

func (m *senderMaps) Close() error {
	return _SenderClose(
		m.Hist,
		m.Output,
	)
}

// senderVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type senderVariables struct {
}

// senderPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type senderPrograms struct {
	SenderIn  *ebpf.Program `ebpf:"sender_in"`
	SenderOut *ebpf.Program `ebpf:"sender_out"`
}

func (p *senderPrograms) Close() error {
	return _SenderClose(
		p.SenderIn,
		p.SenderOut,
	)
}

func _SenderClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sender_bpfel.o
var _SenderBytes []byte
