{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stamp-bpf.sender.fullname" . }}
  namespace: {{ include "stamp-bpf.namespace" . }}
  labels:
    {{- include "stamp-bpf.labels" . | nindent 4 }}
    app.kubernetes.io/component: sender
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stamp-bpf.reflector.fullname" . }}
  namespace: {{ include "stamp-bpf.namespace" . }}
  labels:
    {{- include "stamp-bpf.labels" . | nindent 4 }}
    app.kubernetes.io/component: reflector
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}